volumes:
  nextcloud-db:
  nextcloud:
  lamconfig:
  ldap:
  slapd:

networks:
  network-nextcloud:

services:
  ldap-account-manager:
    container_name: ldap-account-manager
    build:
      context: .
    image: ldapaccountmanager/lam:9.0
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - lamconfig:/var/lib/ldap-account-manager/config
    environment:
      - LAM_PASSWORD=${LAM_PASSWORD}
      - LAM_LANG=en_US
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USER=cn=admin,${LDAP_BASE_DN}
      - DEBUG=true
    hostname: ldap-account-manager
    networks: 
      - network-nextcloud

  ldap:
    container_name: ldap
    image: osixia/openldap:latest
    restart: unless-stopped
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_VERIFY_CLIENT=never
    command: "--loglevel info --copy-service"
    volumes:
      - ldap:/var/lib/ldap
      - slapd:/etc/ldap/slapd.d
      - ./freeradius/docker/certificates:/container/service/slapd/assets/certs
    hostname: ldap
    networks: 
      - network-nextcloud

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud123
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud123
    networks:
      - network-nextcloud

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8000:80
    links:
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_PASSWORD: nextcloud123
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: nextcloud-db
    networks:
      - network-nextcloud
